### PR TITLE
Make rio-tiler-mvt an optional import

### LINKED ISSUE #14: mvtEncoder as optional import
I think including `mvtEncoder` makes the dependency bundle a bit larger? Because it has to include `vtzero` and maybe a couple other packages...?

The mvt encoding is probably not used by all users, so having it be an optional import and optional dependency would be great.

You could force install with
```
pip install cogeo-mosaic-tiler[mvt]
```

### PR DESCRIPTION
**Pull request by kylebarron**
Closes #14

Do you want any additional `try/except` there?

### CODE REVIEW

**Comment by kylebarron** [comment]
I fixed the merge conflict on this. Should be straightforward. Do you want an edit on the README too?

**Comment by kylebarron** [comment]
Tests seem to be failing on master now...? You might need to update the CI config to also install `rio-tiler-mvt`

**Comment by vincentsarago** [comment]
🤦

**Comment by kylebarron** [comment]
I don't know why CI didn't run on this PR?

**Comment by vincentsarago** [comment]
because I have to enable them ;-)

**Pull request merged**
